### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jisamcom** [Slyyxp/BugsPy#11]
```
python bugs.py -u https://music.bugs.co.kr/artist/3373
Client      : INFO     Login Successful
Bugs        : INFO     Artist: 이은미 | Album Count: 149
Bugs        : INFO     Downloading Album #1 of #149.
Bugs        : INFO     Album: 이은미 - 흠뻑 [2019.09.25].
Bugs        : INFO     Track: 2. 어제 낮
100%|█████████████████████████████████████| 25.7M/25.7M [00:07<00:00, 3.62MB/s] Traceback (most recent call last):
  File "bugs.py", line 202, in <module>
    main()
  File "bugs.py", line 191, in main
    artist_rip(artist_id=id)
  File "bugs.py", line 54, in artist_rip
    album_rip(album['album_id'])
  File "bugs.py", line 97, in album_rip
    tag(album=meta, track=track, file_path=post_path, cover_path=cover_path)
  File "bugs.py", line 144, in tag
    f_file.save()
  File "C:\Python38\lib\site-packages\mutagen\_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\mutagen\_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "C:\Python38\lib\site-packages\mutagen\flac.py", line 848, in save
    self._save(filething, self.metadata_blocks, deleteid3, padding)
  File "C:\Python38\lib\site-packages\mutagen\flac.py", line 864, in _save
    data = MetadataBlock._writeblocks(
  File "C:\Python38\lib\site-packages\mutagen\flac.py", line 154, in _writeblocks
    data += cls._writeblock(block)
  File "C:\Python38\lib\site-packages\mutagen\flac.py", line 137, in _writeblock

    raise error("block is too long to write")
mutagen.flac.error: block is too long to write

```

**Comment by Slyyxp** [comment]
I cannot seem to recreate this error.
Try running this once more after deleting existing files, if the issue persists post logs.

**Comment by jisamcom** [comment]
if album cover file is too big ( like over 30MB ), and set album cover as 'original' in config, then it causes error.

**Comment by Slyyxp** [comment]
Understood. Thank you for the information.

**Comment by Slyyxp** [comment]
Closed with https://github.com/Slyyxp/BugsPy/commit/6803c360afa62200ab74c7b174ec9148f6094eb1
Worth noting that this commit has been marked for some additional cleanup as this solution could and should be handled more elegantly within the tag() function.
